import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ShoppingList from "@/components/ShoppingList";
import Cards from "@/components/Cards";
import Clicker from "@/components/Clicker";
import StateArray from "@/components/StateArray";
import StateWithInput from "@/components/StateWithInput";
import DependentEffect from "@/components/DependentEffect";

import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>React tutorial</p>
        </div>
        <LoadDataFromBlockchain />
        <DependentEffect />
        <StateWithInput />
        <StateArray />
        <Clicker />
        <Cards />
        <ShoppingList />
      </main>
    </>
  );
}

function LoadDataFromBlockchain() {
  const [data, setData] = useState("");
  const [loading, setLoading] = useState(false);
  async function loadData() {
    setLoading(true);
    const data = await apiCall();
    setData(data);
    setLoading(false);
  }

  useEffect(() => {
    loadData();
  }, []);

  return <div>{loading ? "Loading..." : data}</div>;
}

async function apiCall() {
  return new Promise((resolve) => {
    setTimeout(() => resolve("Hello from blockchain!"), 1000);
  });
}
